import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import Blogs from './blogs';

export default function Home() {
  const [blogs, setBlogs] = useState(null);
  // const [comments, setComments] = useState(null);

  const fetchBlogs = async () => {
    const rawData = await fetch('http://localhost:3009');
    const data = await rawData.json();
    return setBlogs(data);
  };

  useEffect(() => {
    fetchBlogs();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Blogs blogs={blogs} />
    </div>
  );
}
